# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ui_gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ui_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ui_gateway.proto\x12\x12rovi.ui_gateway.v1\"\x0f\n\rStatusRequest\"k\n\x0cStatusUpdate\x12\x19\n\x11timestamp_unix_ms\x18\x01 \x01(\x03\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x13\n\x0b\x63pu_percent\x18\x03 \x01(\x02\x12\x13\n\tvoltage_v\x18\x04 \x01(\x02H\x00\x42\t\n\x07voltage2_\n\tUiGateway\x12R\n\tGetStatus\x12!.rovi.ui_gateway.v1.StatusRequest\x1a .rovi.ui_gateway.v1.StatusUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ui_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=40
  _globals['_STATUSREQUEST']._serialized_end=55
  _globals['_STATUSUPDATE']._serialized_start=57
  _globals['_STATUSUPDATE']._serialized_end=164
  _globals['_UIGATEWAY']._serialized_start=166
  _globals['_UIGATEWAY']._serialized_end=261
# @@protoc_insertion_point(module_scope)
