# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ui_bridge_pb2 as ui__bridge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ui_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UiBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/roblibs.ui_bridge.v1.UiBridge/GetStatus',
                request_serializer=ui__bridge__pb2.StatusRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.StatusSnapshot.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/StreamStatus',
                request_serializer=ui__bridge__pb2.StatusRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.StartStack = channel.unary_unary(
                '/roblibs.ui_bridge.v1.UiBridge/StartStack',
                request_serializer=ui__bridge__pb2.StackControlRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.StackControlResponse.FromString,
                _registered_method=True)
        self.StopStack = channel.unary_unary(
                '/roblibs.ui_bridge.v1.UiBridge/StopStack',
                request_serializer=ui__bridge__pb2.StackControlRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.StackControlResponse.FromString,
                _registered_method=True)
        self.RestartStack = channel.unary_unary(
                '/roblibs.ui_bridge.v1.UiBridge/RestartStack',
                request_serializer=ui__bridge__pb2.StackControlRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.StackControlResponse.FromString,
                _registered_method=True)
        self.GetStackStatus = channel.unary_unary(
                '/roblibs.ui_bridge.v1.UiBridge/GetStackStatus',
                request_serializer=ui__bridge__pb2.StackStatusRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.StackStatus.FromString,
                _registered_method=True)
        self.ListStacks = channel.unary_unary(
                '/roblibs.ui_bridge.v1.UiBridge/ListStacks',
                request_serializer=ui__bridge__pb2.ListStacksRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.ListStacksResponse.FromString,
                _registered_method=True)
        self.StreamRobotState = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/StreamRobotState',
                request_serializer=ui__bridge__pb2.RobotStateRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.RobotStateUpdate.FromString,
                _registered_method=True)
        self.StreamLidar = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/StreamLidar',
                request_serializer=ui__bridge__pb2.LidarRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.LidarUpdate.FromString,
                _registered_method=True)
        self.StreamMap = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/StreamMap',
                request_serializer=ui__bridge__pb2.MapRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.MapUpdate.FromString,
                _registered_method=True)
        self.StreamFloorTopology = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/StreamFloorTopology',
                request_serializer=ui__bridge__pb2.FloorTopologyRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.FloorTopologyUpdate.FromString,
                _registered_method=True)
        self.GetRobotModelMeta = channel.unary_unary(
                '/roblibs.ui_bridge.v1.UiBridge/GetRobotModelMeta',
                request_serializer=ui__bridge__pb2.RobotModelRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.RobotModelMeta.FromString,
                _registered_method=True)
        self.GetRobotModel = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/GetRobotModel',
                request_serializer=ui__bridge__pb2.RobotModelRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.RobotModelChunk.FromString,
                _registered_method=True)


class UiBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Returns a single status snapshot (includes metadata).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Streams status updates (values only; no metadata).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStack(self, request, context):
        """--- Stack control (Phase 5; optional / may be disabled by config) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartStack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStackStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRobotState(self, request, context):
        """Streams robot pose + wheel joint angles for 3D rendering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLidar(self, request, context):
        """Streams downsampled lidar scans for 3D visualization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMap(self, request, context):
        """Streams an encoded occupancy grid map suitable for UI rendering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFloorTopology(self, request, context):
        """Streams floor topology suitable for UI rendering (best-effort; idle when topic is absent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotModelMeta(self, request, context):
        """Returns metadata for the current robot model (no GLB bytes).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotModel(self, request, context):
        """Returns the robot model as a GLB (binary glTF) stream (chunked to avoid gRPC message size limits).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UiBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=ui__bridge__pb2.StatusRequest.FromString,
                    response_serializer=ui__bridge__pb2.StatusSnapshot.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=ui__bridge__pb2.StatusRequest.FromString,
                    response_serializer=ui__bridge__pb2.StatusUpdate.SerializeToString,
            ),
            'StartStack': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStack,
                    request_deserializer=ui__bridge__pb2.StackControlRequest.FromString,
                    response_serializer=ui__bridge__pb2.StackControlResponse.SerializeToString,
            ),
            'StopStack': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStack,
                    request_deserializer=ui__bridge__pb2.StackControlRequest.FromString,
                    response_serializer=ui__bridge__pb2.StackControlResponse.SerializeToString,
            ),
            'RestartStack': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartStack,
                    request_deserializer=ui__bridge__pb2.StackControlRequest.FromString,
                    response_serializer=ui__bridge__pb2.StackControlResponse.SerializeToString,
            ),
            'GetStackStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStackStatus,
                    request_deserializer=ui__bridge__pb2.StackStatusRequest.FromString,
                    response_serializer=ui__bridge__pb2.StackStatus.SerializeToString,
            ),
            'ListStacks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStacks,
                    request_deserializer=ui__bridge__pb2.ListStacksRequest.FromString,
                    response_serializer=ui__bridge__pb2.ListStacksResponse.SerializeToString,
            ),
            'StreamRobotState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRobotState,
                    request_deserializer=ui__bridge__pb2.RobotStateRequest.FromString,
                    response_serializer=ui__bridge__pb2.RobotStateUpdate.SerializeToString,
            ),
            'StreamLidar': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLidar,
                    request_deserializer=ui__bridge__pb2.LidarRequest.FromString,
                    response_serializer=ui__bridge__pb2.LidarUpdate.SerializeToString,
            ),
            'StreamMap': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMap,
                    request_deserializer=ui__bridge__pb2.MapRequest.FromString,
                    response_serializer=ui__bridge__pb2.MapUpdate.SerializeToString,
            ),
            'StreamFloorTopology': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFloorTopology,
                    request_deserializer=ui__bridge__pb2.FloorTopologyRequest.FromString,
                    response_serializer=ui__bridge__pb2.FloorTopologyUpdate.SerializeToString,
            ),
            'GetRobotModelMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotModelMeta,
                    request_deserializer=ui__bridge__pb2.RobotModelRequest.FromString,
                    response_serializer=ui__bridge__pb2.RobotModelMeta.SerializeToString,
            ),
            'GetRobotModel': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRobotModel,
                    request_deserializer=ui__bridge__pb2.RobotModelRequest.FromString,
                    response_serializer=ui__bridge__pb2.RobotModelChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'roblibs.ui_bridge.v1.UiBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('roblibs.ui_bridge.v1.UiBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UiBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/GetStatus',
            ui__bridge__pb2.StatusRequest.SerializeToString,
            ui__bridge__pb2.StatusSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StreamStatus',
            ui__bridge__pb2.StatusRequest.SerializeToString,
            ui__bridge__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StartStack',
            ui__bridge__pb2.StackControlRequest.SerializeToString,
            ui__bridge__pb2.StackControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StopStack',
            ui__bridge__pb2.StackControlRequest.SerializeToString,
            ui__bridge__pb2.StackControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/RestartStack',
            ui__bridge__pb2.StackControlRequest.SerializeToString,
            ui__bridge__pb2.StackControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStackStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/GetStackStatus',
            ui__bridge__pb2.StackStatusRequest.SerializeToString,
            ui__bridge__pb2.StackStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/ListStacks',
            ui__bridge__pb2.ListStacksRequest.SerializeToString,
            ui__bridge__pb2.ListStacksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StreamRobotState',
            ui__bridge__pb2.RobotStateRequest.SerializeToString,
            ui__bridge__pb2.RobotStateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLidar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StreamLidar',
            ui__bridge__pb2.LidarRequest.SerializeToString,
            ui__bridge__pb2.LidarUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StreamMap',
            ui__bridge__pb2.MapRequest.SerializeToString,
            ui__bridge__pb2.MapUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFloorTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StreamFloorTopology',
            ui__bridge__pb2.FloorTopologyRequest.SerializeToString,
            ui__bridge__pb2.FloorTopologyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotModelMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/GetRobotModelMeta',
            ui__bridge__pb2.RobotModelRequest.SerializeToString,
            ui__bridge__pb2.RobotModelMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/GetRobotModel',
            ui__bridge__pb2.RobotModelRequest.SerializeToString,
            ui__bridge__pb2.RobotModelChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
