# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ui_bridge_pb2 as ui__bridge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ui_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UiBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/GetStatus',
                request_serializer=ui__bridge__pb2.StatusRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.StreamRobotState = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/StreamRobotState',
                request_serializer=ui__bridge__pb2.RobotStateRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.RobotStateUpdate.FromString,
                _registered_method=True)
        self.GetRobotModel = channel.unary_stream(
                '/roblibs.ui_bridge.v1.UiBridge/GetRobotModel',
                request_serializer=ui__bridge__pb2.RobotModelRequest.SerializeToString,
                response_deserializer=ui__bridge__pb2.RobotModelChunk.FromString,
                _registered_method=True)


class UiBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Streams periodic status snapshots at a globally-configured cadence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRobotState(self, request, context):
        """Streams robot pose + wheel joint angles for 3D rendering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotModel(self, request, context):
        """Returns the robot model as a GLB (binary glTF) stream (chunked to avoid gRPC message size limits).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UiBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=ui__bridge__pb2.StatusRequest.FromString,
                    response_serializer=ui__bridge__pb2.StatusUpdate.SerializeToString,
            ),
            'StreamRobotState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRobotState,
                    request_deserializer=ui__bridge__pb2.RobotStateRequest.FromString,
                    response_serializer=ui__bridge__pb2.RobotStateUpdate.SerializeToString,
            ),
            'GetRobotModel': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRobotModel,
                    request_deserializer=ui__bridge__pb2.RobotModelRequest.FromString,
                    response_serializer=ui__bridge__pb2.RobotModelChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'roblibs.ui_bridge.v1.UiBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('roblibs.ui_bridge.v1.UiBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UiBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/GetStatus',
            ui__bridge__pb2.StatusRequest.SerializeToString,
            ui__bridge__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/StreamRobotState',
            ui__bridge__pb2.RobotStateRequest.SerializeToString,
            ui__bridge__pb2.RobotStateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/roblibs.ui_bridge.v1.UiBridge/GetRobotModel',
            ui__bridge__pb2.RobotModelRequest.SerializeToString,
            ui__bridge__pb2.RobotModelChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
